server:
  port: 8089
  servlet:
    context-path: /shop
    multipart:
      max-file-size: 10MB  #单个文件
      max-request-size: 100MB #总文件大小



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_mybatis?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true
  mvc:
    # 不指定静态资源的目录的话，默认有许多个，这里指定的话，就相当改默认值了
    #static-path-pattern: classpath:/haha
    view:
      prefix: /
      suffix: .html
      #prefix: /WEB-INF/views/
      #suffix: .jsp

    # 访问静态资源需要带上前缀，默认不需要前缀
    # static-path-pattern: /res/**
  redis:
    database: 0 #数据库索引
    host: 127.0.0.1  #远程redis服务器的地址 当前redis是在我们本机打开 所以localhost即可
    port: 6379 #连接redis端口  redis默认开放在6379端口
    password: # 默认为空
    jedis.pool.max-idle: 100 #最大空闲连接
    jedis.pool.max-wait: -1ms
    max-active: -1 #最大连接数(负数表示没有限制)
    jedis.pool.min.idle: 2
    timeout: 5000 #连接超时时间，连接redis数据库 超过这个时间的话 就连接不成功

  profiles:
    active: local
  # kafka相关配置
  kafka:
    bootstrap-servers: 10.252.176.6:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      acks: 1
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false


    #mybatis:
  # 由于引入了MP 由MP来扫描配置项了  （Mybatis一些配置 MP不兼容
  # mapper-locations: classpath:mapper/**/*.xml
  # type-aliases-package: com.sph.practice.mybatis
  #configuration:
    #开启驼峰映射
    #map-underscore-to-camel-case: true
    #指定Mybatis应如何自动映射列到字段或属性，NONE标识关闭自动映射；PARTIAL只会自动映射没有定义嵌套结果映射的字段。FULL会自动映射任何复杂的结果集（无论是否嵌套），默认值是PARTIAL，我们可以在resultMap标签使用autoMapping=true。标签指定优先级比较好，全局配置优先级稍低
    #auto-mapping-behavior: full
  main:
    allow-bean-definition-overriding: true


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sph.practice.mybatis, com.sph.practice.mybatisplus
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰映射
    map-underscore-to-camel-case: true


#devtools插件
devtools:
  restart:
    enabled: true #是否支持热部署

#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  #分页合理化参数，默认值为false。当参数设置为true时，pageNum<=0时会查询第一页，pageNum>pages(超过总数时)，会查询最后一页。
  reasonable: true
  #支持通过Mapper接口来传递分页参数
  support-methods-arguments: true

# 打印sql  //由于引入MP 不生效了
#logging:
#  level:
#    com.sph.practice.mybatis.mapper: DEBUG

iothub:
  edge:
    url: tcp://159.75.100.238:1884
    username: M988OTSSKVXRay1;12010126;0URF8;1659926494
    password: 7e3cbff5cb0daf08705a5e98323dc1865fbe8bbbdfbc7ebfa49ae6db660f9029;hmacsha256
    client-id: M988OTSSKVXRay1
    default-topic: M988OTSSKV/XRay1/test
    completionTimeout: 60000
  center:
    url: tcp://159.75.100.238:1883
    username: M988OTSSKVXRayReceiver;12010126;2OJTG;1659910371
    password: e0bb81db6b5413bf476c4af99e1a2f00e9cc17c200fce29400241775a47b9aaa;hmacsha256
    client-id: M988OTSSKVXRayReceiver
    default-topic: M988OTSSKV/XRayReceiver/data
    completion-timeout: 60000

switch: true

