// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KafkaFaceImgDto.proto
package com.sph.practice.component.boot.kafka.pojo.dto.capture;

public final class FaceImgProto {
    private FaceImgProto() {}

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface KafkaFaceImgDtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:KafkaFaceImgDto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 数据来源
         * </pre>
         *
         * <code>string dataSource = 1;</code>
         */
        java.lang.String getDataSource();

        /**
         * <pre>
         * 数据来源
         * </pre>
         *
         * <code>string dataSource = 1;</code>
         */
        com.google.protobuf.ByteString
        getDataSourceBytes();

        /**
         * <pre>
         * 设备编号，国标码
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         */
        java.lang.String getDeviceId();

        /**
         * <pre>
         * 设备编号，国标码
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         */
        com.google.protobuf.ByteString
        getDeviceIdBytes();

        /**
         * <pre>
         * 设备商
         * </pre>
         *
         * <code>string manufacturer = 3;</code>
         */
        java.lang.String getManufacturer();

        /**
         * <pre>
         * 设备商
         * </pre>
         *
         * <code>string manufacturer = 3;</code>
         */
        com.google.protobuf.ByteString
        getManufacturerBytes();

        /**
         * <pre>
         * 抓拍小图url
         * </pre>
         *
         * <code>string imgMinUrl = 4;</code>
         */
        java.lang.String getImgMinUrl();

        /**
         * <pre>
         * 抓拍小图url
         * </pre>
         *
         * <code>string imgMinUrl = 4;</code>
         */
        com.google.protobuf.ByteString
        getImgMinUrlBytes();

        /**
         * <pre>
         * 抓拍大图url
         * </pre>
         *
         * <code>string imgMaxUrl = 5;</code>
         */
        java.lang.String getImgMaxUrl();

        /**
         * <pre>
         * 抓拍大图url
         * </pre>
         *
         * <code>string imgMaxUrl = 5;</code>
         */
        com.google.protobuf.ByteString
        getImgMaxUrlBytes();

        /**
         * <pre>
         * 抓拍时间
         * </pre>
         *
         * <code>fixed64 imgTime = 6;</code>
         */
        long getImgTime();

        /**
         * <pre>
         * 数据接收时的时间戳
         * </pre>
         *
         * <code>fixed64 serverReceiveTime = 7;</code>
         */
        long getServerReceiveTime();
    }

    /**
     * <pre>
     * 人脸图片信息信息
     * </pre>
     * <p>
     * Protobuf type {@code KafkaFaceImgDto}
     */
    public static final class KafkaFaceImgDto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:KafkaFaceImgDto)
            KafkaFaceImgDtoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use KafkaFaceImgDto.newBuilder() to construct.
        private KafkaFaceImgDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private KafkaFaceImgDto() {
            dataSource_ = "";
            deviceId_ = "";
            manufacturer_ = "";
            imgMinUrl_ = "";
            imgMaxUrl_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new KafkaFaceImgDto();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private KafkaFaceImgDto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            dataSource_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            deviceId_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            manufacturer_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            imgMinUrl_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            imgMaxUrl_ = s;
                            break;
                        }
                        case 49: {

                            imgTime_ = input.readFixed64();
                            break;
                        }
                        case 57: {

                            serverReceiveTime_ = input.readFixed64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return FaceImgProto.internal_static_KafkaFaceImgDto_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return FaceImgProto.internal_static_KafkaFaceImgDto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            FaceImgProto.KafkaFaceImgDto.class, FaceImgProto.KafkaFaceImgDto.Builder.class);
        }

        public static final int DATASOURCE_FIELD_NUMBER = 1;
        private volatile java.lang.Object dataSource_;

        /**
         * <pre>
         * 数据来源
         * </pre>
         *
         * <code>string dataSource = 1;</code>
         */
        public java.lang.String getDataSource() {
            java.lang.Object ref = dataSource_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dataSource_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 数据来源
         * </pre>
         *
         * <code>string dataSource = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDataSourceBytes() {
            java.lang.Object ref = dataSource_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dataSource_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DEVICEID_FIELD_NUMBER = 2;
        private volatile java.lang.Object deviceId_;

        /**
         * <pre>
         * 设备编号，国标码
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         */
        public java.lang.String getDeviceId() {
            java.lang.Object ref = deviceId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deviceId_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 设备编号，国标码
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         */
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            java.lang.Object ref = deviceId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MANUFACTURER_FIELD_NUMBER = 3;
        private volatile java.lang.Object manufacturer_;

        /**
         * <pre>
         * 设备商
         * </pre>
         *
         * <code>string manufacturer = 3;</code>
         */
        public java.lang.String getManufacturer() {
            java.lang.Object ref = manufacturer_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                manufacturer_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 设备商
         * </pre>
         *
         * <code>string manufacturer = 3;</code>
         */
        public com.google.protobuf.ByteString
        getManufacturerBytes() {
            java.lang.Object ref = manufacturer_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                manufacturer_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IMGMINURL_FIELD_NUMBER = 4;
        private volatile java.lang.Object imgMinUrl_;

        /**
         * <pre>
         * 抓拍小图url
         * </pre>
         *
         * <code>string imgMinUrl = 4;</code>
         */
        public java.lang.String getImgMinUrl() {
            java.lang.Object ref = imgMinUrl_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                imgMinUrl_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 抓拍小图url
         * </pre>
         *
         * <code>string imgMinUrl = 4;</code>
         */
        public com.google.protobuf.ByteString
        getImgMinUrlBytes() {
            java.lang.Object ref = imgMinUrl_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                imgMinUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IMGMAXURL_FIELD_NUMBER = 5;
        private volatile java.lang.Object imgMaxUrl_;

        /**
         * <pre>
         * 抓拍大图url
         * </pre>
         *
         * <code>string imgMaxUrl = 5;</code>
         */
        public java.lang.String getImgMaxUrl() {
            java.lang.Object ref = imgMaxUrl_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                imgMaxUrl_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 抓拍大图url
         * </pre>
         *
         * <code>string imgMaxUrl = 5;</code>
         */
        public com.google.protobuf.ByteString
        getImgMaxUrlBytes() {
            java.lang.Object ref = imgMaxUrl_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                imgMaxUrl_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IMGTIME_FIELD_NUMBER = 6;
        private long imgTime_;

        /**
         * <pre>
         * 抓拍时间
         * </pre>
         *
         * <code>fixed64 imgTime = 6;</code>
         */
        public long getImgTime() {
            return imgTime_;
        }

        public static final int SERVERRECEIVETIME_FIELD_NUMBER = 7;
        private long serverReceiveTime_;

        /**
         * <pre>
         * 数据接收时的时间戳
         * </pre>
         *
         * <code>fixed64 serverReceiveTime = 7;</code>
         */
        public long getServerReceiveTime() {
            return serverReceiveTime_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getDataSourceBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataSource_);
            }
            if (!getDeviceIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
            }
            if (!getManufacturerBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, manufacturer_);
            }
            if (!getImgMinUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imgMinUrl_);
            }
            if (!getImgMaxUrlBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, imgMaxUrl_);
            }
            if (imgTime_ != 0L) {
                output.writeFixed64(6, imgTime_);
            }
            if (serverReceiveTime_ != 0L) {
                output.writeFixed64(7, serverReceiveTime_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getDataSourceBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataSource_);
            }
            if (!getDeviceIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
            }
            if (!getManufacturerBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, manufacturer_);
            }
            if (!getImgMinUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imgMinUrl_);
            }
            if (!getImgMaxUrlBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, imgMaxUrl_);
            }
            if (imgTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFixed64Size(6, imgTime_);
            }
            if (serverReceiveTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFixed64Size(7, serverReceiveTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof FaceImgProto.KafkaFaceImgDto)) {
                return super.equals(obj);
            }
            FaceImgProto.KafkaFaceImgDto other = (FaceImgProto.KafkaFaceImgDto) obj;

            if (!getDataSource()
                    .equals(other.getDataSource())) return false;
            if (!getDeviceId()
                    .equals(other.getDeviceId())) return false;
            if (!getManufacturer()
                    .equals(other.getManufacturer())) return false;
            if (!getImgMinUrl()
                    .equals(other.getImgMinUrl())) return false;
            if (!getImgMaxUrl()
                    .equals(other.getImgMaxUrl())) return false;
            if (getImgTime()
                    != other.getImgTime()) return false;
            if (getServerReceiveTime()
                    != other.getServerReceiveTime()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + DATASOURCE_FIELD_NUMBER;
            hash = (53 * hash) + getDataSource().hashCode();
            hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
            hash = (53 * hash) + getDeviceId().hashCode();
            hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
            hash = (53 * hash) + getManufacturer().hashCode();
            hash = (37 * hash) + IMGMINURL_FIELD_NUMBER;
            hash = (53 * hash) + getImgMinUrl().hashCode();
            hash = (37 * hash) + IMGMAXURL_FIELD_NUMBER;
            hash = (53 * hash) + getImgMaxUrl().hashCode();
            hash = (37 * hash) + IMGTIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getImgTime());
            hash = (37 * hash) + SERVERRECEIVETIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getServerReceiveTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static FaceImgProto.KafkaFaceImgDto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static FaceImgProto.KafkaFaceImgDto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static FaceImgProto.KafkaFaceImgDto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(FaceImgProto.KafkaFaceImgDto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 人脸图片信息信息
         * </pre>
         * <p>
         * Protobuf type {@code KafkaFaceImgDto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:KafkaFaceImgDto)
                FaceImgProto.KafkaFaceImgDtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return FaceImgProto.internal_static_KafkaFaceImgDto_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return FaceImgProto.internal_static_KafkaFaceImgDto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                FaceImgProto.KafkaFaceImgDto.class, FaceImgProto.KafkaFaceImgDto.Builder.class);
            }

            // Construct using FaceImgProto.KafkaFaceImgDto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                dataSource_ = "";

                deviceId_ = "";

                manufacturer_ = "";

                imgMinUrl_ = "";

                imgMaxUrl_ = "";

                imgTime_ = 0L;

                serverReceiveTime_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return FaceImgProto.internal_static_KafkaFaceImgDto_descriptor;
            }

            @java.lang.Override
            public FaceImgProto.KafkaFaceImgDto getDefaultInstanceForType() {
                return FaceImgProto.KafkaFaceImgDto.getDefaultInstance();
            }

            @java.lang.Override
            public FaceImgProto.KafkaFaceImgDto build() {
                FaceImgProto.KafkaFaceImgDto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public FaceImgProto.KafkaFaceImgDto buildPartial() {
                FaceImgProto.KafkaFaceImgDto result = new FaceImgProto.KafkaFaceImgDto(this);
                result.dataSource_ = dataSource_;
                result.deviceId_ = deviceId_;
                result.manufacturer_ = manufacturer_;
                result.imgMinUrl_ = imgMinUrl_;
                result.imgMaxUrl_ = imgMaxUrl_;
                result.imgTime_ = imgTime_;
                result.serverReceiveTime_ = serverReceiveTime_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof FaceImgProto.KafkaFaceImgDto) {
                    return mergeFrom((FaceImgProto.KafkaFaceImgDto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(FaceImgProto.KafkaFaceImgDto other) {
                if (other == FaceImgProto.KafkaFaceImgDto.getDefaultInstance()) return this;
                if (!other.getDataSource().isEmpty()) {
                    dataSource_ = other.dataSource_;
                    onChanged();
                }
                if (!other.getDeviceId().isEmpty()) {
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (!other.getManufacturer().isEmpty()) {
                    manufacturer_ = other.manufacturer_;
                    onChanged();
                }
                if (!other.getImgMinUrl().isEmpty()) {
                    imgMinUrl_ = other.imgMinUrl_;
                    onChanged();
                }
                if (!other.getImgMaxUrl().isEmpty()) {
                    imgMaxUrl_ = other.imgMaxUrl_;
                    onChanged();
                }
                if (other.getImgTime() != 0L) {
                    setImgTime(other.getImgTime());
                }
                if (other.getServerReceiveTime() != 0L) {
                    setServerReceiveTime(other.getServerReceiveTime());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                FaceImgProto.KafkaFaceImgDto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (FaceImgProto.KafkaFaceImgDto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object dataSource_ = "";

            /**
             * <pre>
             * 数据来源
             * </pre>
             *
             * <code>string dataSource = 1;</code>
             */
            public java.lang.String getDataSource() {
                java.lang.Object ref = dataSource_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    dataSource_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 数据来源
             * </pre>
             *
             * <code>string dataSource = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDataSourceBytes() {
                java.lang.Object ref = dataSource_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    dataSource_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 数据来源
             * </pre>
             *
             * <code>string dataSource = 1;</code>
             */
            public Builder setDataSource(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                dataSource_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 数据来源
             * </pre>
             *
             * <code>string dataSource = 1;</code>
             */
            public Builder clearDataSource() {

                dataSource_ = getDefaultInstance().getDataSource();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 数据来源
             * </pre>
             *
             * <code>string dataSource = 1;</code>
             */
            public Builder setDataSourceBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                dataSource_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object deviceId_ = "";

            /**
             * <pre>
             * 设备编号，国标码
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             */
            public java.lang.String getDeviceId() {
                java.lang.Object ref = deviceId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    deviceId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 设备编号，国标码
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             */
            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                java.lang.Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 设备编号，国标码
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             */
            public Builder setDeviceId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                deviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 设备编号，国标码
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             */
            public Builder clearDeviceId() {

                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 设备编号，国标码
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             */
            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                deviceId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object manufacturer_ = "";

            /**
             * <pre>
             * 设备商
             * </pre>
             *
             * <code>string manufacturer = 3;</code>
             */
            public java.lang.String getManufacturer() {
                java.lang.Object ref = manufacturer_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    manufacturer_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 设备商
             * </pre>
             *
             * <code>string manufacturer = 3;</code>
             */
            public com.google.protobuf.ByteString
            getManufacturerBytes() {
                java.lang.Object ref = manufacturer_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    manufacturer_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 设备商
             * </pre>
             *
             * <code>string manufacturer = 3;</code>
             */
            public Builder setManufacturer(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                manufacturer_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 设备商
             * </pre>
             *
             * <code>string manufacturer = 3;</code>
             */
            public Builder clearManufacturer() {

                manufacturer_ = getDefaultInstance().getManufacturer();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 设备商
             * </pre>
             *
             * <code>string manufacturer = 3;</code>
             */
            public Builder setManufacturerBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                manufacturer_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object imgMinUrl_ = "";

            /**
             * <pre>
             * 抓拍小图url
             * </pre>
             *
             * <code>string imgMinUrl = 4;</code>
             */
            public java.lang.String getImgMinUrl() {
                java.lang.Object ref = imgMinUrl_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    imgMinUrl_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 抓拍小图url
             * </pre>
             *
             * <code>string imgMinUrl = 4;</code>
             */
            public com.google.protobuf.ByteString
            getImgMinUrlBytes() {
                java.lang.Object ref = imgMinUrl_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    imgMinUrl_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 抓拍小图url
             * </pre>
             *
             * <code>string imgMinUrl = 4;</code>
             */
            public Builder setImgMinUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                imgMinUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 抓拍小图url
             * </pre>
             *
             * <code>string imgMinUrl = 4;</code>
             */
            public Builder clearImgMinUrl() {

                imgMinUrl_ = getDefaultInstance().getImgMinUrl();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 抓拍小图url
             * </pre>
             *
             * <code>string imgMinUrl = 4;</code>
             */
            public Builder setImgMinUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                imgMinUrl_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object imgMaxUrl_ = "";

            /**
             * <pre>
             * 抓拍大图url
             * </pre>
             *
             * <code>string imgMaxUrl = 5;</code>
             */
            public java.lang.String getImgMaxUrl() {
                java.lang.Object ref = imgMaxUrl_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    imgMaxUrl_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 抓拍大图url
             * </pre>
             *
             * <code>string imgMaxUrl = 5;</code>
             */
            public com.google.protobuf.ByteString
            getImgMaxUrlBytes() {
                java.lang.Object ref = imgMaxUrl_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    imgMaxUrl_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 抓拍大图url
             * </pre>
             *
             * <code>string imgMaxUrl = 5;</code>
             */
            public Builder setImgMaxUrl(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                imgMaxUrl_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 抓拍大图url
             * </pre>
             *
             * <code>string imgMaxUrl = 5;</code>
             */
            public Builder clearImgMaxUrl() {

                imgMaxUrl_ = getDefaultInstance().getImgMaxUrl();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 抓拍大图url
             * </pre>
             *
             * <code>string imgMaxUrl = 5;</code>
             */
            public Builder setImgMaxUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                imgMaxUrl_ = value;
                onChanged();
                return this;
            }

            private long imgTime_;

            /**
             * <pre>
             * 抓拍时间
             * </pre>
             *
             * <code>fixed64 imgTime = 6;</code>
             */
            public long getImgTime() {
                return imgTime_;
            }

            /**
             * <pre>
             * 抓拍时间
             * </pre>
             *
             * <code>fixed64 imgTime = 6;</code>
             */
            public Builder setImgTime(long value) {

                imgTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 抓拍时间
             * </pre>
             *
             * <code>fixed64 imgTime = 6;</code>
             */
            public Builder clearImgTime() {

                imgTime_ = 0L;
                onChanged();
                return this;
            }

            private long serverReceiveTime_;

            /**
             * <pre>
             * 数据接收时的时间戳
             * </pre>
             *
             * <code>fixed64 serverReceiveTime = 7;</code>
             */
            public long getServerReceiveTime() {
                return serverReceiveTime_;
            }

            /**
             * <pre>
             * 数据接收时的时间戳
             * </pre>
             *
             * <code>fixed64 serverReceiveTime = 7;</code>
             */
            public Builder setServerReceiveTime(long value) {

                serverReceiveTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 数据接收时的时间戳
             * </pre>
             *
             * <code>fixed64 serverReceiveTime = 7;</code>
             */
            public Builder clearServerReceiveTime() {

                serverReceiveTime_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:KafkaFaceImgDto)
        }

        // @@protoc_insertion_point(class_scope:KafkaFaceImgDto)
        private static final FaceImgProto.KafkaFaceImgDto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new FaceImgProto.KafkaFaceImgDto();
        }

        public static FaceImgProto.KafkaFaceImgDto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<KafkaFaceImgDto>
                PARSER = new com.google.protobuf.AbstractParser<KafkaFaceImgDto>() {
            @java.lang.Override
            public KafkaFaceImgDto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new KafkaFaceImgDto(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<KafkaFaceImgDto> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<KafkaFaceImgDto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public FaceImgProto.KafkaFaceImgDto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_KafkaFaceImgDto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_KafkaFaceImgDto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\022FaceImgProto.proto\"\237\001\n\017KafkaFaceImgDto" +
                        "\022\022\n\ndataSource\030\001 \001(\t\022\020\n\010deviceId\030\002 \001(\t\022\024" +
                        "\n\014manufacturer\030\003 \001(\t\022\021\n\timgMinUrl\030\004 \001(\t\022" +
                        "\021\n\timgMaxUrl\030\005 \001(\t\022\017\n\007imgTime\030\006 \001(\006\022\031\n\021s" +
                        "erverReceiveTime\030\007 \001(\006B\016B\014FaceImgProtob\006" +
                        "proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                                                new com.google.protobuf.Descriptors.FileDescriptor[]{
                                                });
        internal_static_KafkaFaceImgDto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_KafkaFaceImgDto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_KafkaFaceImgDto_descriptor,
                new java.lang.String[]{"DataSource", "DeviceId", "Manufacturer", "ImgMinUrl", "ImgMaxUrl", "ImgTime", "ServerReceiveTime",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
