// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KafkaKeyPersonCorrelationDto.proto
package com.sph.practice.component.boot.kafka.pojo.dto.capture;

public final class FaceAlarmProto {
    private FaceAlarmProto() {}

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface KafkaKeyPersonCorrelationDtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:KafkaKeyPersonCorrelationDto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 重点人员主键
         * </pre>
         *
         * <code>fixed64 empId = 1;</code>
         */
        long getEmpId();

        /**
         * <pre>
         * 特性主键 ID
         * </pre>
         *
         * <code>fixed64 correlationId = 2;</code>
         */
        long getCorrelationId();

        /**
         * <pre>
         * 特性类型
         * </pre>
         *
         * <code>fixed32 correlationType = 3;</code>
         */
        int getCorrelationType();

        /**
         * <pre>
         * 特性类型内容
         * </pre>
         *
         * <code>string correlationContent = 4;</code>
         */
        java.lang.String getCorrelationContent();

        /**
         * <pre>
         * 特性类型内容
         * </pre>
         *
         * <code>string correlationContent = 4;</code>
         */
        com.google.protobuf.ByteString
        getCorrelationContentBytes();

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>fixed64 sendTime = 5;</code>
         */
        long getSendTime();
    }

    /**
     * <pre>
     * 布控人员信息
     * </pre>
     * <p>
     * Protobuf type {@code KafkaKeyPersonCorrelationDto}
     */
    public static final class KafkaKeyPersonCorrelationDto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:KafkaKeyPersonCorrelationDto)
            KafkaKeyPersonCorrelationDtoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use KafkaKeyPersonCorrelationDto.newBuilder() to construct.
        private KafkaKeyPersonCorrelationDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private KafkaKeyPersonCorrelationDto() {
            correlationContent_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new KafkaKeyPersonCorrelationDto();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private KafkaKeyPersonCorrelationDto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 9: {

                            empId_ = input.readFixed64();
                            break;
                        }
                        case 17: {

                            correlationId_ = input.readFixed64();
                            break;
                        }
                        case 29: {

                            correlationType_ = input.readFixed32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            correlationContent_ = s;
                            break;
                        }
                        case 41: {

                            sendTime_ = input.readFixed64();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return FaceAlarmProto.internal_static_KafkaKeyPersonCorrelationDto_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return FaceAlarmProto.internal_static_KafkaKeyPersonCorrelationDto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            FaceAlarmProto.KafkaKeyPersonCorrelationDto.class, FaceAlarmProto.KafkaKeyPersonCorrelationDto.Builder.class);
        }

        public static final int EMPID_FIELD_NUMBER = 1;
        private long empId_;

        /**
         * <pre>
         * 重点人员主键
         * </pre>
         *
         * <code>fixed64 empId = 1;</code>
         */
        public long getEmpId() {
            return empId_;
        }

        public static final int CORRELATIONID_FIELD_NUMBER = 2;
        private long correlationId_;

        /**
         * <pre>
         * 特性主键 ID
         * </pre>
         *
         * <code>fixed64 correlationId = 2;</code>
         */
        public long getCorrelationId() {
            return correlationId_;
        }

        public static final int CORRELATIONTYPE_FIELD_NUMBER = 3;
        private int correlationType_;

        /**
         * <pre>
         * 特性类型
         * </pre>
         *
         * <code>fixed32 correlationType = 3;</code>
         */
        public int getCorrelationType() {
            return correlationType_;
        }

        public static final int CORRELATIONCONTENT_FIELD_NUMBER = 4;
        private volatile java.lang.Object correlationContent_;

        /**
         * <pre>
         * 特性类型内容
         * </pre>
         *
         * <code>string correlationContent = 4;</code>
         */
        public java.lang.String getCorrelationContent() {
            java.lang.Object ref = correlationContent_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                correlationContent_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 特性类型内容
         * </pre>
         *
         * <code>string correlationContent = 4;</code>
         */
        public com.google.protobuf.ByteString
        getCorrelationContentBytes() {
            java.lang.Object ref = correlationContent_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                correlationContent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SENDTIME_FIELD_NUMBER = 5;
        private long sendTime_;

        /**
         * <pre>
         * 发送时间
         * </pre>
         *
         * <code>fixed64 sendTime = 5;</code>
         */
        public long getSendTime() {
            return sendTime_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (empId_ != 0L) {
                output.writeFixed64(1, empId_);
            }
            if (correlationId_ != 0L) {
                output.writeFixed64(2, correlationId_);
            }
            if (correlationType_ != 0) {
                output.writeFixed32(3, correlationType_);
            }
            if (!getCorrelationContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, correlationContent_);
            }
            if (sendTime_ != 0L) {
                output.writeFixed64(5, sendTime_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (empId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFixed64Size(1, empId_);
            }
            if (correlationId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFixed64Size(2, correlationId_);
            }
            if (correlationType_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFixed32Size(3, correlationType_);
            }
            if (!getCorrelationContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, correlationContent_);
            }
            if (sendTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFixed64Size(5, sendTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof FaceAlarmProto.KafkaKeyPersonCorrelationDto)) {
                return super.equals(obj);
            }
            FaceAlarmProto.KafkaKeyPersonCorrelationDto other = (FaceAlarmProto.KafkaKeyPersonCorrelationDto) obj;

            if (getEmpId()
                    != other.getEmpId()) return false;
            if (getCorrelationId()
                    != other.getCorrelationId()) return false;
            if (getCorrelationType()
                    != other.getCorrelationType()) return false;
            if (!getCorrelationContent()
                    .equals(other.getCorrelationContent())) return false;
            if (getSendTime()
                    != other.getSendTime()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + EMPID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getEmpId());
            hash = (37 * hash) + CORRELATIONID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getCorrelationId());
            hash = (37 * hash) + CORRELATIONTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getCorrelationType();
            hash = (37 * hash) + CORRELATIONCONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getCorrelationContent().hashCode();
            hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSendTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(FaceAlarmProto.KafkaKeyPersonCorrelationDto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 布控人员信息
         * </pre>
         * <p>
         * Protobuf type {@code KafkaKeyPersonCorrelationDto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:KafkaKeyPersonCorrelationDto)
                FaceAlarmProto.KafkaKeyPersonCorrelationDtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return FaceAlarmProto.internal_static_KafkaKeyPersonCorrelationDto_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return FaceAlarmProto.internal_static_KafkaKeyPersonCorrelationDto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                FaceAlarmProto.KafkaKeyPersonCorrelationDto.class, FaceAlarmProto.KafkaKeyPersonCorrelationDto.Builder.class);
            }

            // Construct using FaceAlarmProto.KafkaKeyPersonCorrelationDto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                empId_ = 0L;

                correlationId_ = 0L;

                correlationType_ = 0;

                correlationContent_ = "";

                sendTime_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return FaceAlarmProto.internal_static_KafkaKeyPersonCorrelationDto_descriptor;
            }

            @java.lang.Override
            public FaceAlarmProto.KafkaKeyPersonCorrelationDto getDefaultInstanceForType() {
                return FaceAlarmProto.KafkaKeyPersonCorrelationDto.getDefaultInstance();
            }

            @java.lang.Override
            public FaceAlarmProto.KafkaKeyPersonCorrelationDto build() {
                FaceAlarmProto.KafkaKeyPersonCorrelationDto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public FaceAlarmProto.KafkaKeyPersonCorrelationDto buildPartial() {
                FaceAlarmProto.KafkaKeyPersonCorrelationDto result = new FaceAlarmProto.KafkaKeyPersonCorrelationDto(this);
                result.empId_ = empId_;
                result.correlationId_ = correlationId_;
                result.correlationType_ = correlationType_;
                result.correlationContent_ = correlationContent_;
                result.sendTime_ = sendTime_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof FaceAlarmProto.KafkaKeyPersonCorrelationDto) {
                    return mergeFrom((FaceAlarmProto.KafkaKeyPersonCorrelationDto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(FaceAlarmProto.KafkaKeyPersonCorrelationDto other) {
                if (other == FaceAlarmProto.KafkaKeyPersonCorrelationDto.getDefaultInstance()) return this;
                if (other.getEmpId() != 0L) {
                    setEmpId(other.getEmpId());
                }
                if (other.getCorrelationId() != 0L) {
                    setCorrelationId(other.getCorrelationId());
                }
                if (other.getCorrelationType() != 0) {
                    setCorrelationType(other.getCorrelationType());
                }
                if (!other.getCorrelationContent().isEmpty()) {
                    correlationContent_ = other.correlationContent_;
                    onChanged();
                }
                if (other.getSendTime() != 0L) {
                    setSendTime(other.getSendTime());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                FaceAlarmProto.KafkaKeyPersonCorrelationDto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (FaceAlarmProto.KafkaKeyPersonCorrelationDto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long empId_;

            /**
             * <pre>
             * 重点人员主键
             * </pre>
             *
             * <code>fixed64 empId = 1;</code>
             */
            public long getEmpId() {
                return empId_;
            }

            /**
             * <pre>
             * 重点人员主键
             * </pre>
             *
             * <code>fixed64 empId = 1;</code>
             */
            public Builder setEmpId(long value) {

                empId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 重点人员主键
             * </pre>
             *
             * <code>fixed64 empId = 1;</code>
             */
            public Builder clearEmpId() {

                empId_ = 0L;
                onChanged();
                return this;
            }

            private long correlationId_;

            /**
             * <pre>
             * 特性主键 ID
             * </pre>
             *
             * <code>fixed64 correlationId = 2;</code>
             */
            public long getCorrelationId() {
                return correlationId_;
            }

            /**
             * <pre>
             * 特性主键 ID
             * </pre>
             *
             * <code>fixed64 correlationId = 2;</code>
             */
            public Builder setCorrelationId(long value) {

                correlationId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 特性主键 ID
             * </pre>
             *
             * <code>fixed64 correlationId = 2;</code>
             */
            public Builder clearCorrelationId() {

                correlationId_ = 0L;
                onChanged();
                return this;
            }

            private int correlationType_;

            /**
             * <pre>
             * 特性类型
             * </pre>
             *
             * <code>fixed32 correlationType = 3;</code>
             */
            public int getCorrelationType() {
                return correlationType_;
            }

            /**
             * <pre>
             * 特性类型
             * </pre>
             *
             * <code>fixed32 correlationType = 3;</code>
             */
            public Builder setCorrelationType(int value) {

                correlationType_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 特性类型
             * </pre>
             *
             * <code>fixed32 correlationType = 3;</code>
             */
            public Builder clearCorrelationType() {

                correlationType_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object correlationContent_ = "";

            /**
             * <pre>
             * 特性类型内容
             * </pre>
             *
             * <code>string correlationContent = 4;</code>
             */
            public java.lang.String getCorrelationContent() {
                java.lang.Object ref = correlationContent_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    correlationContent_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 特性类型内容
             * </pre>
             *
             * <code>string correlationContent = 4;</code>
             */
            public com.google.protobuf.ByteString
            getCorrelationContentBytes() {
                java.lang.Object ref = correlationContent_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    correlationContent_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 特性类型内容
             * </pre>
             *
             * <code>string correlationContent = 4;</code>
             */
            public Builder setCorrelationContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                correlationContent_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 特性类型内容
             * </pre>
             *
             * <code>string correlationContent = 4;</code>
             */
            public Builder clearCorrelationContent() {

                correlationContent_ = getDefaultInstance().getCorrelationContent();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 特性类型内容
             * </pre>
             *
             * <code>string correlationContent = 4;</code>
             */
            public Builder setCorrelationContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                correlationContent_ = value;
                onChanged();
                return this;
            }

            private long sendTime_;

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>fixed64 sendTime = 5;</code>
             */
            public long getSendTime() {
                return sendTime_;
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>fixed64 sendTime = 5;</code>
             */
            public Builder setSendTime(long value) {

                sendTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 发送时间
             * </pre>
             *
             * <code>fixed64 sendTime = 5;</code>
             */
            public Builder clearSendTime() {

                sendTime_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:KafkaKeyPersonCorrelationDto)
        }

        // @@protoc_insertion_point(class_scope:KafkaKeyPersonCorrelationDto)
        private static final FaceAlarmProto.KafkaKeyPersonCorrelationDto DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new FaceAlarmProto.KafkaKeyPersonCorrelationDto();
        }

        public static FaceAlarmProto.KafkaKeyPersonCorrelationDto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<KafkaKeyPersonCorrelationDto>
                PARSER = new com.google.protobuf.AbstractParser<KafkaKeyPersonCorrelationDto>() {
            @java.lang.Override
            public KafkaKeyPersonCorrelationDto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new KafkaKeyPersonCorrelationDto(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<KafkaKeyPersonCorrelationDto> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<KafkaKeyPersonCorrelationDto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public FaceAlarmProto.KafkaKeyPersonCorrelationDto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_KafkaKeyPersonCorrelationDto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_KafkaKeyPersonCorrelationDto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\"KafkaKeyPersonCorrelationDto.proto\"\213\001\n" +
                        "\034KafkaKeyPersonCorrelationDto\022\r\n\005empId\030\001" +
                        " \001(\006\022\025\n\rcorrelationId\030\002 \001(\006\022\027\n\017correlati" +
                        "onType\030\003 \001(\007\022\032\n\022correlationContent\030\004 \001(\t" +
                        "\022\020\n\010sendTime\030\005 \001(\006B\020B\016FaceAlarmProtob\006pr" +
                        "oto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                                                new com.google.protobuf.Descriptors.FileDescriptor[]{
                                                });
        internal_static_KafkaKeyPersonCorrelationDto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_KafkaKeyPersonCorrelationDto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_KafkaKeyPersonCorrelationDto_descriptor,
                new java.lang.String[]{"EmpId", "CorrelationId", "CorrelationType", "CorrelationContent", "SendTime",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
